language: php

php:
    - "5.5"
    - "5.2"

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=3.6 WP_MULTISITE=0
    - WP_VERSION=3.6 WP_MULTISITE=1

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit